# Generated by Django 5.0.3 on 2024-03-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='is_verified',
        ),
    ]
