# Generated by Django 5.0.3 on 2024-03-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='has_rider',
            field=models.BooleanField(default=False),
        ),
    ]
