# Generated by Django 5.0.3 on 2024-03-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_delivery_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
